//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagNobile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2J47NIG\\NOFARPOD;Initial Catalog=Diagnobile_Database;Integrat" +
            "ed Security=True")]
        public string Diagnobile_DatabaseConnectionString {
            get {
                return ((string)(this["Diagnobile_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Diagnobile_Da" +
            "tabase.mdf;Integrated Security=True;Connect Timeout=30")]
        public string Diagnobile_DatabaseString {
            get {
                return ((string)(this["Diagnobile_DatabaseString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\cohen\\Documents\\Diag" +
            "nobile_Database.mdf;Integrated Security=True;Connect Timeout=30")]
        public string Diagnobile_DatabaseConnectionString1 {
            get {
                return ((string)(this["Diagnobile_DatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"C:\\Users\\nofar\\Desktop\\מערכו" +
            "ת מידע\\שנה ג\\סמסטר ב\\פרוייקט גמר\\Documents\\Diagnobile_Database.mdf\";Integrated S" +
            "ecurity=True;Connect Timeout=30")]
        public string Diagnobile_DatabaseNew {
            get {
                return ((string)(this["Diagnobile_DatabaseNew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"C:\\Users\\nofar\\Desktop\\מערכו" +
            "ת מידע\\שנה ג\\סמסטר ב\\פרוייקט גמר\\DiagNobileSofi\\DiagNobile\\Diagnobile_Database.m" +
            "df\";Integrated Security=True;Connect Timeout=30")]
        public string Diagnobile_DatabaseConnectionString2 {
            get {
                return ((string)(this["Diagnobile_DatabaseConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"C:\\Users\\nofar\\Desktop\\מערכו" +
            "ת מידע\\שנה ג\\סמסטר ב\\פרוייקט גמר\\DiagNobileMaayan28.8\\Diagnobile_Database.mdf\";I" +
            "ntegrated Security=True;Connect Timeout=30")]
        public string Diagnobile_Database {
            get {
                return ((string)(this["Diagnobile_Database"]));
            }
        }
    }
}
